[workspace]
resolver = "2"
members = [ "coco", "core", "tui" ]

[workspace.package]
version = "0.0.0-alpha.0"
description = "🥥 » coco » an interactive cli for creating conventional commits."
authors = ["Lucas Colombo <lucas@lucode.ar>"]
readme = "README.md"
edition = "2021"

[profile.release]
strip = "symbols"
lto = "fat"
codegen-units = 1
opt-level = "z"
panic = "abort"
rpath = false
overflow-checks = false
debug = 0
debug-assertions = false

[workspace.dependencies]
indoc = "2.0.5"
matetui = "0.3.2"
eyre = { version = "0.6.12", default-features = false, features = [
    "auto-install",
] }
lool = { git = "https://github.com/lucodear/lool", version = "0.9.0", features = [
    "cli.stylize"
] }
strum = { version = "0.26.1", features = ["derive"] }
serde = { version = "1.0.210", features = ["derive"] }
tokio = { version = "1.40.0", features = [
    "tokio-macros",
    "macros",
    "rt-multi-thread",
    "sync",
    "time",
] }
